'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Class Issue_Details1

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
        Friend Sub New()
            MyBase.New()
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory.Issue Details", GetType(Issue_Details1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = Value
            End Set
        End Property

        Friend Shared ReadOnly Property btn_validation_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_validation.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property btn_validation_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_validation.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property btn_validation_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_validation.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property CBO_SELECTALL_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("CBO_SELECTALL.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property CBO_SELECTALL_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("CBO_SELECTALL.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property CBO_SELECTALL_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("CBO_SELECTALL.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cbo_Storelocation_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cbo_Storelocation.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cbo_Storelocation_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cbo_Storelocation.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property cbo_Storelocation_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cbo_Storelocation.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_excel_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_excel.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_excel_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_excel.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_excel_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_excel.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_item_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_item.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_item_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_item.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_item_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_item.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_SelectAllGroup_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_SelectAllGroup.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_SelectAllGroup_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_SelectAllGroup.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property chk_SelectAllGroup_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chk_SelectAllGroup.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllItem_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllItem.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllItem_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllItem.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllItem_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllItem.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllStore_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllStore.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllStore_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllStore.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Chk_SelectAllStore_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Chk_SelectAllStore.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_groupdesc_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_groupdesc.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_groupdesc_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_groupdesc.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_groupdesc_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_groupdesc.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_itemdetails_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_itemdetails.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_itemdetails_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_itemdetails.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property chklist_itemdetails_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklist_itemdetails.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklst_Store_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklst_Store.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property chklst_Store_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chklst_Store.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property chklst_Store_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chklst_Store.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property ChkRATE_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("ChkRATE.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property ChkRATE_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ChkRATE.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property ChkRATE_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("ChkRATE.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Clear_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Clear.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Clear_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Clear.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Clear_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Clear.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Exit_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Exit.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Exit_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Exit.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Exit_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Exit.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_export_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_export.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_export_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_export.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_export_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_export.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_ITEMFROM_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_ITEMFROM.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_ITEMFROM_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_ITEMFROM.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_ITEMFROM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_ITEMFROM.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_ITEMFROM_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_ITEMFROM.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_itemto_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_itemto.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_itemto_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_itemto.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_itemto_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_itemto.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property cmd_itemto_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd_itemto.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Print_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Print.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Print_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Print.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_Print_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_Print.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_View_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_View.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_View_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_View.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Cmd_View_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmd_View.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Fromdate_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Fromdate.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Fromdate_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Fromdate.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Fromdate_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Fromdate.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Todate_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Todate.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Todate_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Todate.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property dtp_Todate_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("dtp_Todate.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property frmbut_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("frmbut.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox1_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox1.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox2_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox2.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox3_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox3.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property GroupBox4_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupBox4.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_orderby_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_orderby.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_DrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.DrawGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_GridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.GridSize", resourceCulture)
                Return CType(obj, System.Drawing.Size)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property grp_SalebillChecklist_SnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_SalebillChecklist.SnapToGrid", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label1_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label1_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label1_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label10_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label10.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label10_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label10.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label10_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label10.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label2_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label2_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label2_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label3_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label3_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label3_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label4_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label4.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label4_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label4.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label4_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label4.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label6_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label6.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label6_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label6.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label6_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label6.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label7_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label7.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label7_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label7.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label7_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label7.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label8_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label8.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label8_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label8.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label8_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label8.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label9_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label9.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Label9_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label9.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Label9_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Label9.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Heading_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Heading.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Heading_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Heading.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Heading_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Heading.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Itemlist_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Itemlist.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Itemlist_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Itemlist.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Itemlist_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Itemlist.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Storelocation_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Storelocation.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Storelocation_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Storelocation.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Storelocation_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Storelocation.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Lbl_SubledgerCode_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Lbl_SubledgerCode.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Lbl_SubledgerCode_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Lbl_SubledgerCode.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property Lbl_SubledgerCode_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Lbl_SubledgerCode.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Wait_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Wait.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Wait_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Wait.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property lbl_Wait_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_Wait.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox1_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox1_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox1_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox3_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox3_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox3_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox3_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox4_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox4.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox4_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox4.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox4_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox4.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox4_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox4.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox5_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox5.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox5_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox5.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox5_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox5.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox5_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox5.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox6_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox6.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox6_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox6.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox6_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox6.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property PictureBox6_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox6.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property ProgressBar1_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgressBar1.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property ProgressBar1_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgressBar1.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property ProgressBar1_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgressBar1.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_code_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_code.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_code_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_code.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_code_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_code.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_name_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_name.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_name_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_name.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property rdo_name_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rdo_name.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Timer1_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer1.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property Timer1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer1.Location", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Friend Shared ReadOnly Property Timer1_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer1.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property TXT_FROM_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("TXT_FROM.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property TXT_FROM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("TXT_FROM.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property TXT_FROM_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("TXT_FROM.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property txt_itemto_DefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("txt_itemto.DefaultModifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property

        Friend Shared ReadOnly Property txt_itemto_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("txt_itemto.Locked", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Friend Shared ReadOnly Property txt_itemto_Modifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("txt_itemto.Modifiers", resourceCulture)
                Return CType(obj, System.CodeDom.MemberAttributes)
            End Get
        End Property
    End Class
End Namespace
