'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CHS2008;Initial Catalog=KGA1314;User ID=sa;Password=RAU_1234")>  _
        Public ReadOnly Property KGA1314ConnectionString() As String
            Get
                Return CType(Me("KGA1314ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DELLCHS;Initial Catalog=TEST;User ID=sa;Password=clubman")>  _
        Public ReadOnly Property TESTConnectionString() As String
            Get
                Return CType(Me("TESTConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GANESH-PC\CLUBMANDB;Initial Catalog=KGA1314;Persist Security Info=Tru"& _ 
            "e;User ID=sa;Password=123")>  _
        Public ReadOnly Property KGA1314ConnectionString1() As String
            Get
                Return CType(Me("KGA1314ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CHSLAPTOP\MSSQL2008;Initial Catalog=KGA1314NEW;User ID=sa;Password=12"& _ 
            "3")>  _
        Public ReadOnly Property KGA1314NEWConnectionString() As String
            Get
                Return CType(Me("KGA1314NEWConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=RSIHYD1415;User ID=sa;Password=123")>  _
        Public ReadOnly Property RSIHYD1415ConnectionString() As String
            Get
                Return CType(Me("RSIHYD1415ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANISH-PC\BHANU;Initial Catalog=rsihyd1415;Persist Security Info=True"& _ 
            ";User ID=sa;Password=BHANU!@#$%")>  _
        Public ReadOnly Property rsihyd1415ConnectionString1() As String
            Get
                Return CType(Me("rsihyd1415ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANISH-PC\BHANU;Initial Catalog=MCEME@27082014;Persist Security Info="& _ 
            "True;User ID=sa;Password=BHANU!@#$%")>  _
        Public ReadOnly Property MCEME_27082014ConnectionString() As String
            Get
                Return CType(Me("MCEME_27082014ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANISH-PC\BHANU;Initial Catalog=RSI;Persist Security Info=True;User I"& _ 
            "D=sa;Password=BHANU!@#$%")>  _
        Public ReadOnly Property RSIConnectionString() As String
            Get
                Return CType(Me("RSIConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=tarun-pc;Initial Catalog=kolkata;Integrated Security=True")>  _
        Public ReadOnly Property kolkataConnectionString() As String
            Get
                Return CType(Me("kolkataConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TARUN-PC\SA;Initial Catalog=kinv;User ID=sa;Password=123")>  _
        Public ReadOnly Property kinvConnectionString() As String
            Get
                Return CType(Me("kinvConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TARUN-PC\SA;Initial Catalog=KOLKATA1;User ID=SA;Password=123")>  _
        Public ReadOnly Property KOLKATA1ConnectionString() As String
            Get
                Return CType(Me("KOLKATA1ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TARUN-PC\SA;Initial Catalog=ascapay;User ID=SA;Password=123")>  _
        Public ReadOnly Property ascapayConnectionString() As String
            Get
                Return CType(Me("ascapayConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TARUN-PC\SA;Initial Catalog=KOLKATA1;Integrated Security=True")>  _
        Public ReadOnly Property KOLKATA1ConnectionString1() As String
            Get
                Return CType(Me("KOLKATA1ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CHS-PC\CHSSER;Initial Catalog=CCL1516;User ID=sa;Password=123")>  _
        Public ReadOnly Property CCL1516ConnectionString() As String
            Get
                Return CType(Me("CCL1516ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SUDARSHAN;Initial Catalog=CCL1516;Persist Security Info=True;User ID="& _ 
            "SA;Password=123")>  _
        Public ReadOnly Property CCL1516ConnectionString1() As String
            Get
                Return CType(Me("CCL1516ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SUDARSHAN;Initial Catalog=HSR1516;Persist Security Info=True;User ID="& _ 
            "sa;Password=123")>  _
        Public ReadOnly Property HSR1516ConnectionString() As String
            Get
                Return CType(Me("HSR1516ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC;Initial Catalog=CCL1516;User ID=sa;Password=123")>  _
        Public ReadOnly Property CCL1516ConnectionString2() As String
            Get
                Return CType(Me("CCL1516ConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC;Initial Catalog=HSRNEW;Persist Security Info=True;User ID=sa;Pa"& _ 
            "ssword=123")>  _
        Public ReadOnly Property HSRNEWConnectionString() As String
            Get
                Return CType(Me("HSRNEWConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC;Initial Catalog=JHIC1617;Persist Security Info=True;User ID=SA;"& _ 
            "Password=123")>  _
        Public ReadOnly Property JHIC1617ConnectionString() As String
            Get
                Return CType(Me("JHIC1617ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC;Initial Catalog=CCL1617;Persist Security Info=True;User ID=SA;P"& _ 
            "assword=123")>  _
        Public ReadOnly Property CCL1617ConnectionString() As String
            Get
                Return CType(Me("CCL1617ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=IBM;Initial Catalog=MLA1718;Persist Security Info=True;User ID=SA;Pas"& _ 
            "sword=123")>  _
        Public ReadOnly Property MLA1718ConnectionString() As String
            Get
                Return CType(Me("MLA1718ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=IBM;Initial Catalog=CCL1718;User ID=SA;Password=123")>  _
        Public ReadOnly Property CCL1718ConnectionString() As String
            Get
                Return CType(Me("CCL1718ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=IBM;Initial Catalog=MGC1718;Persist Security Info=True;User ID=sa;Pas"& _ 
            "sword=123")>  _
        Public ReadOnly Property MGC1718ConnectionString() As String
            Get
                Return CType(Me("MGC1718ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC\AD;Initial Catalog=ACC1718;Persist Security Info=True;User ID=S"& _ 
            "A;Password=123")>  _
        Public ReadOnly Property ACC1718ConnectionString() As String
            Get
                Return CType(Me("ACC1718ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC\AD;Initial Catalog=CCL1718;Persist Security Info=True;User ID=s"& _ 
            "a;Password=123")>  _
        Public ReadOnly Property CCL1718ConnectionString1() As String
            Get
                Return CType(Me("CCL1718ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AD-PC\AD;Initial Catalog=CCL1718NEW;Persist Security Info=True;User I"& _ 
            "D=sa;Password=123")>  _
        Public ReadOnly Property CCL1718NEWConnectionString() As String
            Get
                Return CType(Me("CCL1718NEWConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=PARDHASARADHI;Initial Catalog=HG1819;Persist Security Info=True;User "& _ 
            "ID=sa;Password=123")>  _
        Public ReadOnly Property HG1819ConnectionString() As String
            Get
                Return CType(Me("HG1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=PARDHASARADHI;Initial Catalog=CPC1819;Persist Security Info=True;User"& _ 
            " ID=sa;Password=123")>  _
        Public ReadOnly Property CPC1819ConnectionString() As String
            Get
                Return CType(Me("CPC1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=PARDHASARADHI;Initial Catalog=BGC1819;User ID=SA;Password=123")>  _
        Public ReadOnly Property BGC1819ConnectionString() As String
            Get
                Return CType(Me("BGC1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANIKANTATULALA\MANISERVER;Initial Catalog=MLRF1819;Persist Security "& _ 
            "Info=True;User ID=SA;Password=123")>  _
        Public ReadOnly Property MLRF1819ConnectionString() As String
            Get
                Return CType(Me("MLRF1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANIKANTATULALA\MANISERVER;Initial Catalog=MLRF1819;Integrated Securi"& _ 
            "ty=True")>  _
        Public ReadOnly Property MLRF1819ConnectionString1() As String
            Get
                Return CType(Me("MLRF1819ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANIKANTATULALA\MANISERVER;Initial Catalog=BGC1819;Integrated Securit"& _ 
            "y=True")>  _
        Public ReadOnly Property BGC1819ConnectionString1() As String
            Get
                Return CType(Me("BGC1819ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MANIKANTA\MANISERVER;Initial Catalog=ACC1819;User ID=SA;Password=123")>  _
        Public ReadOnly Property ACC1819ConnectionString() As String
            Get
                Return CType(Me("ACC1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=milan;Initial Catalog=CFC1920;Persist Security Info=True;User ID=sa;P"& _ 
            "assword=2313")>  _
        Public ReadOnly Property CFC1920ConnectionString() As String
            Get
                Return CType(Me("CFC1920ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=IBM;Initial Catalog=MGC1819;Persist Security Info=True;User ID=SA;Pas"& _ 
            "sword=123")>  _
        Public ReadOnly Property MGC1819ConnectionString() As String
            Get
                Return CType(Me("MGC1819ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\MSSQLSERVER01;Initial Catalog=KGA2021;Persist Security Info=Tr"& _ 
            "ue;User ID=SA;Password=123")>  _
        Public ReadOnly Property KGA2021ConnectionString() As String
            Get
                Return CType(Me("KGA2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\MSSQLSERVER01;Initial Catalog=KIC2021;Persist Security Info=Tr"& _ 
            "ue;User ID=sa;Password=123")>  _
        Public ReadOnly Property KIC2021ConnectionString() As String
            Get
                Return CType(Me("KIC2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\MSSQLSERVER01;Initial Catalog=RGC2021;Persist Security Info=Tr"& _ 
            "ue;User ID=sa;Password=123")>  _
        Public ReadOnly Property RGC2021ConnectionString() As String
            Get
                Return CType(Me("RGC2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\MSSQLSERVER01;Initial Catalog=CCL2021;Persist Security Info=Tr"& _ 
            "ue;User ID=SA;Password=123")>  _
        Public ReadOnly Property CCL2021ConnectionString() As String
            Get
                Return CType(Me("CCL2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\SRIRAM;Initial Catalog=KSCA2021;Persist Security Info=True;Use"& _ 
            "r ID=SA;Password=1996")>  _
        Public ReadOnly Property KSCA2021ConnectionString() As String
            Get
                Return CType(Me("KSCA2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\SRIRAM;Initial Catalog=SKYYE2122;Persist Security Info=True;Us"& _ 
            "er ID=SA;Password=1996")>  _
        Public ReadOnly Property SKYYE2122ConnectionString() As String
            Get
                Return CType(Me("SKYYE2122ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\SRIRAM;Initial Catalog=BRC2122;Persist Security Info=True;User"& _ 
            " ID=sa;Password=1996")>  _
        Public ReadOnly Property BRC2122ConnectionString() As String
            Get
                Return CType(Me("BRC2122ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\SRIRAM;Initial Catalog=HGA2122;Persist Security Info=True;User"& _ 
            " ID=sa;Password=1996")>  _
        Public ReadOnly Property HGA2122ConnectionString() As String
            Get
                Return CType(Me("HGA2122ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=183.82.96.27;Initial Catalog=HGA2122;Persist Security Info=True;User "& _ 
            "ID=SA;Password=ay6kD0(w")>  _
        Public ReadOnly Property HGA2122ConnectionString1() As String
            Get
                Return CType(Me("HGA2122ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SRIRAM\SRIRAM;Initial Catalog=ACC2021;Persist Security Info=True;User"& _ 
            " ID=sa;Password=1996")>  _
        Public ReadOnly Property ACC2021ConnectionString() As String
            Get
                Return CType(Me("ACC2021ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=SHUNMUGAVELU;Initial Catalog=MBC2223;User ID=sa;Password=1234567890")>  _
        Public ReadOnly Property MBC2223ConnectionString() As String
            Get
                Return CType(Me("MBC2223ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-53I62JN\SRIRAM;Initial Catalog=SRI;Persist Security Info=True"& _ 
            ";User ID=SA;Password=1996")>  _
        Public ReadOnly Property SRIConnectionString() As String
            Get
                Return CType(Me("SRIConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-53I62JN\SRIRAM;Initial Catalog=ACC2021;Persist Security Info="& _ 
            "True;User ID=sa;Password=1996")>  _
        Public ReadOnly Property ACC2021ConnectionString1() As String
            Get
                Return CType(Me("ACC2021ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-53I62JN\;Initial Catalog=Sri;Integrated Security=True")>  _
        Public ReadOnly Property SriConnectionString1() As String
            Get
                Return CType(Me("SriConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-53I62JN;Initial Catalog=BGCCURRENT;Persist Security Info=True"& _ 
            ";User ID=sa;Password=1996")>  _
        Public ReadOnly Property BGCCURRENTConnectionString() As String
            Get
                Return CType(Me("BGCCURRENTConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-53I62JN;Initial Catalog=BBSRSMARTCURRENT;Persist Security Inf"& _ 
            "o=True;User ID=sa;Password=1996")>  _
        Public ReadOnly Property BBSRSMARTCURRENTConnectionString() As String
            Get
                Return CType(Me("BBSRSMARTCURRENTConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Inventory.My.MySettings
            Get
                Return Global.Inventory.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
